apiVersion: batch/v1
kind: Job
metadata:
  name: plantnet-baseline
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: plantnet-baseline
    spec:
      restartPolicy: "Never"
      containers:
        - name: plantnet-baseline
          image: registry.datexis.com/s36400/plantnet:v1.8
          imagePullPolicy: "Always"
          ports:
            - name: client-port
              containerPort: 6006
          resources:
            requests:
              nvidia.com/gpu: 1
              memory: "4Gi"
              cpu: "1000m"
            limits:
              nvidia.com/gpu: 1 # requesting 1 GPU
              memory: 40Gi
              cpu: "12000m"
          volumeMounts:
            - name: plantnet-pvc
              mountPath: "/plantnet"
            - name: dshm
              mountPath: /dev/shm
          env:
          - name: PYTHONUNBUFFERED
            value: "0"
          command:
            - /bin/sh
            - "-c"
            - "python main_baseline.py --use_gpu"
      nodeSelector:
        gpu: v100
      imagePullSecrets:
        - name:  private-registry-auth
      volumes:
      - name: plantnet-pvc
        persistentVolumeClaim:
          claimName: plantnet-pvc
      - name: dshm
        emptyDir:
          medium: Memory